//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Tanda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Tanda.WebService3Soap")]
    public interface WebService3Soap {
        
        // CODEGEN: Generating message contract since element name tanda from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionTanda", ReplyAction="*")]
        Universidad.Tanda.SeleccionTandaResponse SeleccionTanda(Universidad.Tanda.SeleccionTandaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionTanda", ReplyAction="*")]
        System.Threading.Tasks.Task<Universidad.Tanda.SeleccionTandaResponse> SeleccionTandaAsync(Universidad.Tanda.SeleccionTandaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionTandaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionTanda", Namespace="http://tempuri.org/", Order=0)]
        public Universidad.Tanda.SeleccionTandaRequestBody Body;
        
        public SeleccionTandaRequest() {
        }
        
        public SeleccionTandaRequest(Universidad.Tanda.SeleccionTandaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionTandaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tanda;
        
        public SeleccionTandaRequestBody() {
        }
        
        public SeleccionTandaRequestBody(string tanda) {
            this.tanda = tanda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionTandaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionTandaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Universidad.Tanda.SeleccionTandaResponseBody Body;
        
        public SeleccionTandaResponse() {
        }
        
        public SeleccionTandaResponse(Universidad.Tanda.SeleccionTandaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionTandaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SeleccionTandaResult;
        
        public SeleccionTandaResponseBody() {
        }
        
        public SeleccionTandaResponseBody(string SeleccionTandaResult) {
            this.SeleccionTandaResult = SeleccionTandaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService3SoapChannel : Universidad.Tanda.WebService3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService3SoapClient : System.ServiceModel.ClientBase<Universidad.Tanda.WebService3Soap>, Universidad.Tanda.WebService3Soap {
        
        public WebService3SoapClient() {
        }
        
        public WebService3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Universidad.Tanda.SeleccionTandaResponse Universidad.Tanda.WebService3Soap.SeleccionTanda(Universidad.Tanda.SeleccionTandaRequest request) {
            return base.Channel.SeleccionTanda(request);
        }
        
        public string SeleccionTanda(string tanda) {
            Universidad.Tanda.SeleccionTandaRequest inValue = new Universidad.Tanda.SeleccionTandaRequest();
            inValue.Body = new Universidad.Tanda.SeleccionTandaRequestBody();
            inValue.Body.tanda = tanda;
            Universidad.Tanda.SeleccionTandaResponse retVal = ((Universidad.Tanda.WebService3Soap)(this)).SeleccionTanda(inValue);
            return retVal.Body.SeleccionTandaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Universidad.Tanda.SeleccionTandaResponse> Universidad.Tanda.WebService3Soap.SeleccionTandaAsync(Universidad.Tanda.SeleccionTandaRequest request) {
            return base.Channel.SeleccionTandaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Universidad.Tanda.SeleccionTandaResponse> SeleccionTandaAsync(string tanda) {
            Universidad.Tanda.SeleccionTandaRequest inValue = new Universidad.Tanda.SeleccionTandaRequest();
            inValue.Body = new Universidad.Tanda.SeleccionTandaRequestBody();
            inValue.Body.tanda = tanda;
            return ((Universidad.Tanda.WebService3Soap)(this)).SeleccionTandaAsync(inValue);
        }
    }
}
