//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Validacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Validacion.WebService2Soap")]
    public interface WebService2Soap {
        
        // CODEGEN: Generating message contract since element name cedula from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCedula", ReplyAction="*")]
        Universidad.Validacion.ValidarCedulaResponse ValidarCedula(Universidad.Validacion.ValidarCedulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCedula", ReplyAction="*")]
        System.Threading.Tasks.Task<Universidad.Validacion.ValidarCedulaResponse> ValidarCedulaAsync(Universidad.Validacion.ValidarCedulaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCedulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCedula", Namespace="http://tempuri.org/", Order=0)]
        public Universidad.Validacion.ValidarCedulaRequestBody Body;
        
        public ValidarCedulaRequest() {
        }
        
        public ValidarCedulaRequest(Universidad.Validacion.ValidarCedulaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCedulaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public ValidarCedulaRequestBody() {
        }
        
        public ValidarCedulaRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCedulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCedulaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Universidad.Validacion.ValidarCedulaResponseBody Body;
        
        public ValidarCedulaResponse() {
        }
        
        public ValidarCedulaResponse(Universidad.Validacion.ValidarCedulaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCedulaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidarCedulaResult;
        
        public ValidarCedulaResponseBody() {
        }
        
        public ValidarCedulaResponseBody(bool ValidarCedulaResult) {
            this.ValidarCedulaResult = ValidarCedulaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : Universidad.Validacion.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<Universidad.Validacion.WebService2Soap>, Universidad.Validacion.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Universidad.Validacion.ValidarCedulaResponse Universidad.Validacion.WebService2Soap.ValidarCedula(Universidad.Validacion.ValidarCedulaRequest request) {
            return base.Channel.ValidarCedula(request);
        }
        
        public bool ValidarCedula(string cedula) {
            Universidad.Validacion.ValidarCedulaRequest inValue = new Universidad.Validacion.ValidarCedulaRequest();
            inValue.Body = new Universidad.Validacion.ValidarCedulaRequestBody();
            inValue.Body.cedula = cedula;
            Universidad.Validacion.ValidarCedulaResponse retVal = ((Universidad.Validacion.WebService2Soap)(this)).ValidarCedula(inValue);
            return retVal.Body.ValidarCedulaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Universidad.Validacion.ValidarCedulaResponse> Universidad.Validacion.WebService2Soap.ValidarCedulaAsync(Universidad.Validacion.ValidarCedulaRequest request) {
            return base.Channel.ValidarCedulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Universidad.Validacion.ValidarCedulaResponse> ValidarCedulaAsync(string cedula) {
            Universidad.Validacion.ValidarCedulaRequest inValue = new Universidad.Validacion.ValidarCedulaRequest();
            inValue.Body = new Universidad.Validacion.ValidarCedulaRequestBody();
            inValue.Body.cedula = cedula;
            return ((Universidad.Validacion.WebService2Soap)(this)).ValidarCedulaAsync(inValue);
        }
    }
}
