//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name MostrarCursoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarCurso", ReplyAction="*")]
        Universidad.ServiceReference1.MostrarCursoResponse MostrarCurso(Universidad.ServiceReference1.MostrarCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarCurso", ReplyAction="*")]
        System.Threading.Tasks.Task<Universidad.ServiceReference1.MostrarCursoResponse> MostrarCursoAsync(Universidad.ServiceReference1.MostrarCursoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarCurso", Namespace="http://tempuri.org/", Order=0)]
        public Universidad.ServiceReference1.MostrarCursoRequestBody Body;
        
        public MostrarCursoRequest() {
        }
        
        public MostrarCursoRequest(Universidad.ServiceReference1.MostrarCursoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarCursoRequestBody {
        
        public MostrarCursoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarCursoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Universidad.ServiceReference1.MostrarCursoResponseBody Body;
        
        public MostrarCursoResponse() {
        }
        
        public MostrarCursoResponse(Universidad.ServiceReference1.MostrarCursoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarCursoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Universidad.ServiceReference1.ArrayOfString MostrarCursoResult;
        
        public MostrarCursoResponseBody() {
        }
        
        public MostrarCursoResponseBody(Universidad.ServiceReference1.ArrayOfString MostrarCursoResult) {
            this.MostrarCursoResult = MostrarCursoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Universidad.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Universidad.ServiceReference1.WebService1Soap>, Universidad.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Universidad.ServiceReference1.MostrarCursoResponse Universidad.ServiceReference1.WebService1Soap.MostrarCurso(Universidad.ServiceReference1.MostrarCursoRequest request) {
            return base.Channel.MostrarCurso(request);
        }
        
        public Universidad.ServiceReference1.ArrayOfString MostrarCurso() {
            Universidad.ServiceReference1.MostrarCursoRequest inValue = new Universidad.ServiceReference1.MostrarCursoRequest();
            inValue.Body = new Universidad.ServiceReference1.MostrarCursoRequestBody();
            Universidad.ServiceReference1.MostrarCursoResponse retVal = ((Universidad.ServiceReference1.WebService1Soap)(this)).MostrarCurso(inValue);
            return retVal.Body.MostrarCursoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Universidad.ServiceReference1.MostrarCursoResponse> Universidad.ServiceReference1.WebService1Soap.MostrarCursoAsync(Universidad.ServiceReference1.MostrarCursoRequest request) {
            return base.Channel.MostrarCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Universidad.ServiceReference1.MostrarCursoResponse> MostrarCursoAsync() {
            Universidad.ServiceReference1.MostrarCursoRequest inValue = new Universidad.ServiceReference1.MostrarCursoRequest();
            inValue.Body = new Universidad.ServiceReference1.MostrarCursoRequestBody();
            return ((Universidad.ServiceReference1.WebService1Soap)(this)).MostrarCursoAsync(inValue);
        }
    }
}
